# Generated by Django 5.0.7 on 2024-09-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('license', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('did', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='driver_photos/')),
            ],
        ),
    ]
