# Generated by Django 5.1.1 on 2024-09-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0002_logisticuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='id',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='photo',
        ),
        migrations.AlterField(
            model_name='driver',
            name='did',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license',
            field=models.ImageField(upload_to='driver_photos/'),
        ),
    ]
