# Generated by Django 5.0.7 on 2024-09-16 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0003_remove_driver_id_remove_driver_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_value', models.IntegerField()),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('redeemed', 'Redeemed')], default='assigned', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistic_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
