# Generated by Django 5.1.1 on 2024-09-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tot_bag', models.CharField(max_length=15)),
                ('bag_wei', models.EmailField(max_length=100)),
                ('tot_wei', models.CharField(max_length=100)),
            ],
        ),
    ]
